// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMU4xmxqSPfLz8A0_fbNG91KyuMGY94dA',
    appId: '1:293150527929:web:40e9f8c07ea7ad9646e668',
    messagingSenderId: '293150527929',
    projectId: 'ia-activity-ff31d',
    authDomain: 'ia-activity-ff31d.firebaseapp.com',
    storageBucket: 'ia-activity-ff31d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5MH8fk8lLTwBg7Ht28WEfj0tprWZ-hOE',
    appId: '1:293150527929:android:d64b290d740d3b3f46e668',
    messagingSenderId: '293150527929',
    projectId: 'ia-activity-ff31d',
    storageBucket: 'ia-activity-ff31d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFZpFNg_Jv2-aF0UJa-CI5vgFuCXOFR-Q',
    appId: '1:293150527929:ios:c120fb28ef0006c446e668',
    messagingSenderId: '293150527929',
    projectId: 'ia-activity-ff31d',
    storageBucket: 'ia-activity-ff31d.appspot.com',
    iosBundleId: 'com.example.aclivite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFZpFNg_Jv2-aF0UJa-CI5vgFuCXOFR-Q',
    appId: '1:293150527929:ios:8e445196ee7dccf546e668',
    messagingSenderId: '293150527929',
    projectId: 'ia-activity-ff31d',
    storageBucket: 'ia-activity-ff31d.appspot.com',
    iosBundleId: 'com.example.aclivite.RunnerTests',
  );
}
